//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 1591

namespace JIIS.Web.Phase3.Tracking.Reports {
    
    
    /// <summary>
    ///Represents a strongly typed in-memory cache of data.
    ///</summary>
    [global::System.Serializable()]
    [global::System.ComponentModel.DesignerCategoryAttribute("code")]
    [global::System.ComponentModel.ToolboxItem(true)]
    [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedDataSetSchema")]
    [global::System.Xml.Serialization.XmlRootAttribute("dsCombinationV3")]
    [global::System.ComponentModel.Design.HelpKeywordAttribute("vs.data.DataSet")]
    public partial class dsCombinationV3 : global::System.Data.DataSet {
        
        private p3_Get_RegStatsByCombinationDataTable tablep3_Get_RegStatsByCombination;
        
        private global::System.Data.SchemaSerializationMode _schemaSerializationMode = global::System.Data.SchemaSerializationMode.IncludeSchema;
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public dsCombinationV3() {
            this.BeginInit();
            this.InitClass();
            global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            base.Relations.CollectionChanged += schemaChangedHandler;
            this.EndInit();
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        protected dsCombinationV3(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
                base(info, context, false) {
            if ((this.IsBinarySerialized(info, context) == true)) {
                this.InitVars(false);
                global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler1 = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
                this.Tables.CollectionChanged += schemaChangedHandler1;
                this.Relations.CollectionChanged += schemaChangedHandler1;
                return;
            }
            string strSchema = ((string)(info.GetValue("XmlSchema", typeof(string))));
            if ((this.DetermineSchemaSerializationMode(info, context) == global::System.Data.SchemaSerializationMode.IncludeSchema)) {
                global::System.Data.DataSet ds = new global::System.Data.DataSet();
                ds.ReadXmlSchema(new global::System.Xml.XmlTextReader(new global::System.IO.StringReader(strSchema)));
                if ((ds.Tables["p3_Get_RegStatsByCombination"] != null)) {
                    base.Tables.Add(new p3_Get_RegStatsByCombinationDataTable(ds.Tables["p3_Get_RegStatsByCombination"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, global::System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXmlSchema(new global::System.Xml.XmlTextReader(new global::System.IO.StringReader(strSchema)));
            }
            this.GetSerializationData(info, context);
            global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        [global::System.ComponentModel.Browsable(false)]
        [global::System.ComponentModel.DesignerSerializationVisibility(global::System.ComponentModel.DesignerSerializationVisibility.Content)]
        public p3_Get_RegStatsByCombinationDataTable p3_Get_RegStatsByCombination {
            get {
                return this.tablep3_Get_RegStatsByCombination;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        [global::System.ComponentModel.BrowsableAttribute(true)]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Visible)]
        public override global::System.Data.SchemaSerializationMode SchemaSerializationMode {
            get {
                return this._schemaSerializationMode;
            }
            set {
                this._schemaSerializationMode = value;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new global::System.Data.DataTableCollection Tables {
            get {
                return base.Tables;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new global::System.Data.DataRelationCollection Relations {
            get {
                return base.Relations;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        protected override void InitializeDerivedDataSet() {
            this.BeginInit();
            this.InitClass();
            this.EndInit();
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public override global::System.Data.DataSet Clone() {
            dsCombinationV3 cln = ((dsCombinationV3)(base.Clone()));
            cln.InitVars();
            cln.SchemaSerializationMode = this.SchemaSerializationMode;
            return cln;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        protected override bool ShouldSerializeTables() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        protected override bool ShouldSerializeRelations() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        protected override void ReadXmlSerializable(global::System.Xml.XmlReader reader) {
            if ((this.DetermineSchemaSerializationMode(reader) == global::System.Data.SchemaSerializationMode.IncludeSchema)) {
                this.Reset();
                global::System.Data.DataSet ds = new global::System.Data.DataSet();
                ds.ReadXml(reader);
                if ((ds.Tables["p3_Get_RegStatsByCombination"] != null)) {
                    base.Tables.Add(new p3_Get_RegStatsByCombinationDataTable(ds.Tables["p3_Get_RegStatsByCombination"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, global::System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXml(reader);
                this.InitVars();
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        protected override global::System.Xml.Schema.XmlSchema GetSchemaSerializable() {
            global::System.IO.MemoryStream stream = new global::System.IO.MemoryStream();
            this.WriteXmlSchema(new global::System.Xml.XmlTextWriter(stream, null));
            stream.Position = 0;
            return global::System.Xml.Schema.XmlSchema.Read(new global::System.Xml.XmlTextReader(stream), null);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        internal void InitVars() {
            this.InitVars(true);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        internal void InitVars(bool initTable) {
            this.tablep3_Get_RegStatsByCombination = ((p3_Get_RegStatsByCombinationDataTable)(base.Tables["p3_Get_RegStatsByCombination"]));
            if ((initTable == true)) {
                if ((this.tablep3_Get_RegStatsByCombination != null)) {
                    this.tablep3_Get_RegStatsByCombination.InitVars();
                }
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        private void InitClass() {
            this.DataSetName = "dsCombinationV3";
            this.Prefix = "";
            this.Namespace = "http://tempuri.org/dsCombinationV3.xsd";
            this.EnforceConstraints = true;
            this.SchemaSerializationMode = global::System.Data.SchemaSerializationMode.IncludeSchema;
            this.tablep3_Get_RegStatsByCombination = new p3_Get_RegStatsByCombinationDataTable();
            base.Tables.Add(this.tablep3_Get_RegStatsByCombination);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        private bool ShouldSerializep3_Get_RegStatsByCombination() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        private void SchemaChanged(object sender, global::System.ComponentModel.CollectionChangeEventArgs e) {
            if ((e.Action == global::System.ComponentModel.CollectionChangeAction.Remove)) {
                this.InitVars();
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedDataSetSchema(global::System.Xml.Schema.XmlSchemaSet xs) {
            dsCombinationV3 ds = new dsCombinationV3();
            global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
            global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
            global::System.Xml.Schema.XmlSchemaAny any = new global::System.Xml.Schema.XmlSchemaAny();
            any.Namespace = ds.Namespace;
            sequence.Items.Add(any);
            type.Particle = sequence;
            global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
            if (xs.Contains(dsSchema.TargetNamespace)) {
                global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
                global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
                try {
                    global::System.Xml.Schema.XmlSchema schema = null;
                    dsSchema.Write(s1);
                    for (global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator(); schemas.MoveNext(); ) {
                        schema = ((global::System.Xml.Schema.XmlSchema)(schemas.Current));
                        s2.SetLength(0);
                        schema.Write(s2);
                        if ((s1.Length == s2.Length)) {
                            s1.Position = 0;
                            s2.Position = 0;
                            for (; ((s1.Position != s1.Length) 
                                        && (s1.ReadByte() == s2.ReadByte())); ) {
                                ;
                            }
                            if ((s1.Position == s1.Length)) {
                                return type;
                            }
                        }
                    }
                }
                finally {
                    if ((s1 != null)) {
                        s1.Close();
                    }
                    if ((s2 != null)) {
                        s2.Close();
                    }
                }
            }
            xs.Add(dsSchema);
            return type;
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public delegate void p3_Get_RegStatsByCombinationRowChangeEventHandler(object sender, p3_Get_RegStatsByCombinationRowChangeEvent e);
        
        /// <summary>
        ///Represents the strongly named DataTable class.
        ///</summary>
        [global::System.Serializable()]
        [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedTableSchema")]
        public partial class p3_Get_RegStatsByCombinationDataTable : global::System.Data.TypedTableBase<p3_Get_RegStatsByCombinationRow> {
            
            private global::System.Data.DataColumn columnCombination;
            
            private global::System.Data.DataColumn columnMunicipalityName;
            
            private global::System.Data.DataColumn columnRegular;
            
            private global::System.Data.DataColumn columnByMail;
            
            private global::System.Data.DataColumn columnAbsentee;
            
            private global::System.Data.DataColumn columnPersonally;
            
            private global::System.Data.DataColumn columnUkupnoPrebrojano;
            
            private global::System.Data.DataColumn columnSpremnoZaBrojanje;
            
            private global::System.Data.DataColumn columnPostaPrebrojano;
            
            private global::System.Data.DataColumn columnOdsustvoPrebrojano;
            
            private global::System.Data.DataColumn columnMobilniPrebrojano;
            
            private global::System.Data.DataColumn columnNepotvrdeniPrebrojano;
            
            private global::System.Data.DataColumn columnPostaSpremnoZaBrojanje;
            
            private global::System.Data.DataColumn columnOdsustvoSpremnoZaBrojanje;
            
            private global::System.Data.DataColumn columnMobilniSpremnoZaBrojanje;
            
            private global::System.Data.DataColumn columnNepotvrdeniSpremnoZaBrojanje;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public p3_Get_RegStatsByCombinationDataTable() {
                this.TableName = "p3_Get_RegStatsByCombination";
                this.BeginInit();
                this.InitClass();
                this.EndInit();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            internal p3_Get_RegStatsByCombinationDataTable(global::System.Data.DataTable table) {
                this.TableName = table.TableName;
                if ((table.CaseSensitive != table.DataSet.CaseSensitive)) {
                    this.CaseSensitive = table.CaseSensitive;
                }
                if ((table.Locale.ToString() != table.DataSet.Locale.ToString())) {
                    this.Locale = table.Locale;
                }
                if ((table.Namespace != table.DataSet.Namespace)) {
                    this.Namespace = table.Namespace;
                }
                this.Prefix = table.Prefix;
                this.MinimumCapacity = table.MinimumCapacity;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected p3_Get_RegStatsByCombinationDataTable(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
                    base(info, context) {
                this.InitVars();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn CombinationColumn {
                get {
                    return this.columnCombination;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn MunicipalityNameColumn {
                get {
                    return this.columnMunicipalityName;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn RegularColumn {
                get {
                    return this.columnRegular;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn ByMailColumn {
                get {
                    return this.columnByMail;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn AbsenteeColumn {
                get {
                    return this.columnAbsentee;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn PersonallyColumn {
                get {
                    return this.columnPersonally;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn UkupnoPrebrojanoColumn {
                get {
                    return this.columnUkupnoPrebrojano;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn SpremnoZaBrojanjeColumn {
                get {
                    return this.columnSpremnoZaBrojanje;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn PostaPrebrojanoColumn {
                get {
                    return this.columnPostaPrebrojano;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn OdsustvoPrebrojanoColumn {
                get {
                    return this.columnOdsustvoPrebrojano;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn MobilniPrebrojanoColumn {
                get {
                    return this.columnMobilniPrebrojano;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn NepotvrdeniPrebrojanoColumn {
                get {
                    return this.columnNepotvrdeniPrebrojano;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn PostaSpremnoZaBrojanjeColumn {
                get {
                    return this.columnPostaSpremnoZaBrojanje;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn OdsustvoSpremnoZaBrojanjeColumn {
                get {
                    return this.columnOdsustvoSpremnoZaBrojanje;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn MobilniSpremnoZaBrojanjeColumn {
                get {
                    return this.columnMobilniSpremnoZaBrojanje;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn NepotvrdeniSpremnoZaBrojanjeColumn {
                get {
                    return this.columnNepotvrdeniSpremnoZaBrojanje;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            [global::System.ComponentModel.Browsable(false)]
            public int Count {
                get {
                    return this.Rows.Count;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public p3_Get_RegStatsByCombinationRow this[int index] {
                get {
                    return ((p3_Get_RegStatsByCombinationRow)(this.Rows[index]));
                }
            }
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public event p3_Get_RegStatsByCombinationRowChangeEventHandler p3_Get_RegStatsByCombinationRowChanging;
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public event p3_Get_RegStatsByCombinationRowChangeEventHandler p3_Get_RegStatsByCombinationRowChanged;
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public event p3_Get_RegStatsByCombinationRowChangeEventHandler p3_Get_RegStatsByCombinationRowDeleting;
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public event p3_Get_RegStatsByCombinationRowChangeEventHandler p3_Get_RegStatsByCombinationRowDeleted;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void Addp3_Get_RegStatsByCombinationRow(p3_Get_RegStatsByCombinationRow row) {
                this.Rows.Add(row);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public p3_Get_RegStatsByCombinationRow Addp3_Get_RegStatsByCombinationRow(
                        string Combination, 
                        string MunicipalityName, 
                        decimal Regular, 
                        decimal ByMail, 
                        decimal Absentee, 
                        decimal Personally, 
                        decimal UkupnoPrebrojano, 
                        decimal SpremnoZaBrojanje, 
                        decimal PostaPrebrojano, 
                        decimal OdsustvoPrebrojano, 
                        decimal MobilniPrebrojano, 
                        decimal NepotvrdeniPrebrojano, 
                        decimal PostaSpremnoZaBrojanje, 
                        decimal OdsustvoSpremnoZaBrojanje, 
                        decimal MobilniSpremnoZaBrojanje, 
                        decimal NepotvrdeniSpremnoZaBrojanje) {
                p3_Get_RegStatsByCombinationRow rowp3_Get_RegStatsByCombinationRow = ((p3_Get_RegStatsByCombinationRow)(this.NewRow()));
                object[] columnValuesArray = new object[] {
                        Combination,
                        MunicipalityName,
                        Regular,
                        ByMail,
                        Absentee,
                        Personally,
                        UkupnoPrebrojano,
                        SpremnoZaBrojanje,
                        PostaPrebrojano,
                        OdsustvoPrebrojano,
                        MobilniPrebrojano,
                        NepotvrdeniPrebrojano,
                        PostaSpremnoZaBrojanje,
                        OdsustvoSpremnoZaBrojanje,
                        MobilniSpremnoZaBrojanje,
                        NepotvrdeniSpremnoZaBrojanje};
                rowp3_Get_RegStatsByCombinationRow.ItemArray = columnValuesArray;
                this.Rows.Add(rowp3_Get_RegStatsByCombinationRow);
                return rowp3_Get_RegStatsByCombinationRow;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public override global::System.Data.DataTable Clone() {
                p3_Get_RegStatsByCombinationDataTable cln = ((p3_Get_RegStatsByCombinationDataTable)(base.Clone()));
                cln.InitVars();
                return cln;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override global::System.Data.DataTable CreateInstance() {
                return new p3_Get_RegStatsByCombinationDataTable();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            internal void InitVars() {
                this.columnCombination = base.Columns["Combination"];
                this.columnMunicipalityName = base.Columns["MunicipalityName"];
                this.columnRegular = base.Columns["Regular"];
                this.columnByMail = base.Columns["ByMail"];
                this.columnAbsentee = base.Columns["Absentee"];
                this.columnPersonally = base.Columns["Personally"];
                this.columnUkupnoPrebrojano = base.Columns["UkupnoPrebrojano"];
                this.columnSpremnoZaBrojanje = base.Columns["SpremnoZaBrojanje"];
                this.columnPostaPrebrojano = base.Columns["PostaPrebrojano"];
                this.columnOdsustvoPrebrojano = base.Columns["OdsustvoPrebrojano"];
                this.columnMobilniPrebrojano = base.Columns["MobilniPrebrojano"];
                this.columnNepotvrdeniPrebrojano = base.Columns["NepotvrdeniPrebrojano"];
                this.columnPostaSpremnoZaBrojanje = base.Columns["PostaSpremnoZaBrojanje"];
                this.columnOdsustvoSpremnoZaBrojanje = base.Columns["OdsustvoSpremnoZaBrojanje"];
                this.columnMobilniSpremnoZaBrojanje = base.Columns["MobilniSpremnoZaBrojanje"];
                this.columnNepotvrdeniSpremnoZaBrojanje = base.Columns["NepotvrdeniSpremnoZaBrojanje"];
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            private void InitClass() {
                this.columnCombination = new global::System.Data.DataColumn("Combination", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnCombination);
                this.columnMunicipalityName = new global::System.Data.DataColumn("MunicipalityName", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnMunicipalityName);
                this.columnRegular = new global::System.Data.DataColumn("Regular", typeof(decimal), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnRegular);
                this.columnByMail = new global::System.Data.DataColumn("ByMail", typeof(decimal), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnByMail);
                this.columnAbsentee = new global::System.Data.DataColumn("Absentee", typeof(decimal), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnAbsentee);
                this.columnPersonally = new global::System.Data.DataColumn("Personally", typeof(decimal), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnPersonally);
                this.columnUkupnoPrebrojano = new global::System.Data.DataColumn("UkupnoPrebrojano", typeof(decimal), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnUkupnoPrebrojano);
                this.columnSpremnoZaBrojanje = new global::System.Data.DataColumn("SpremnoZaBrojanje", typeof(decimal), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnSpremnoZaBrojanje);
                this.columnPostaPrebrojano = new global::System.Data.DataColumn("PostaPrebrojano", typeof(decimal), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnPostaPrebrojano);
                this.columnOdsustvoPrebrojano = new global::System.Data.DataColumn("OdsustvoPrebrojano", typeof(decimal), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnOdsustvoPrebrojano);
                this.columnMobilniPrebrojano = new global::System.Data.DataColumn("MobilniPrebrojano", typeof(decimal), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnMobilniPrebrojano);
                this.columnNepotvrdeniPrebrojano = new global::System.Data.DataColumn("NepotvrdeniPrebrojano", typeof(decimal), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnNepotvrdeniPrebrojano);
                this.columnPostaSpremnoZaBrojanje = new global::System.Data.DataColumn("PostaSpremnoZaBrojanje", typeof(decimal), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnPostaSpremnoZaBrojanje);
                this.columnOdsustvoSpremnoZaBrojanje = new global::System.Data.DataColumn("OdsustvoSpremnoZaBrojanje", typeof(decimal), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnOdsustvoSpremnoZaBrojanje);
                this.columnMobilniSpremnoZaBrojanje = new global::System.Data.DataColumn("MobilniSpremnoZaBrojanje", typeof(decimal), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnMobilniSpremnoZaBrojanje);
                this.columnNepotvrdeniSpremnoZaBrojanje = new global::System.Data.DataColumn("NepotvrdeniSpremnoZaBrojanje", typeof(decimal), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnNepotvrdeniSpremnoZaBrojanje);
                this.columnCombination.MaxLength = 5;
                this.columnMunicipalityName.MaxLength = 50;
                this.columnUkupnoPrebrojano.ReadOnly = true;
                this.columnSpremnoZaBrojanje.ReadOnly = true;
                this.columnPostaPrebrojano.ReadOnly = true;
                this.columnOdsustvoPrebrojano.ReadOnly = true;
                this.columnMobilniPrebrojano.ReadOnly = true;
                this.columnNepotvrdeniPrebrojano.ReadOnly = true;
                this.columnPostaSpremnoZaBrojanje.ReadOnly = true;
                this.columnOdsustvoSpremnoZaBrojanje.ReadOnly = true;
                this.columnMobilniSpremnoZaBrojanje.ReadOnly = true;
                this.columnNepotvrdeniSpremnoZaBrojanje.ReadOnly = true;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public p3_Get_RegStatsByCombinationRow Newp3_Get_RegStatsByCombinationRow() {
                return ((p3_Get_RegStatsByCombinationRow)(this.NewRow()));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override global::System.Data.DataRow NewRowFromBuilder(global::System.Data.DataRowBuilder builder) {
                return new p3_Get_RegStatsByCombinationRow(builder);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override global::System.Type GetRowType() {
                return typeof(p3_Get_RegStatsByCombinationRow);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override void OnRowChanged(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanged(e);
                if ((this.p3_Get_RegStatsByCombinationRowChanged != null)) {
                    this.p3_Get_RegStatsByCombinationRowChanged(this, new p3_Get_RegStatsByCombinationRowChangeEvent(((p3_Get_RegStatsByCombinationRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override void OnRowChanging(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanging(e);
                if ((this.p3_Get_RegStatsByCombinationRowChanging != null)) {
                    this.p3_Get_RegStatsByCombinationRowChanging(this, new p3_Get_RegStatsByCombinationRowChangeEvent(((p3_Get_RegStatsByCombinationRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override void OnRowDeleted(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleted(e);
                if ((this.p3_Get_RegStatsByCombinationRowDeleted != null)) {
                    this.p3_Get_RegStatsByCombinationRowDeleted(this, new p3_Get_RegStatsByCombinationRowChangeEvent(((p3_Get_RegStatsByCombinationRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override void OnRowDeleting(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleting(e);
                if ((this.p3_Get_RegStatsByCombinationRowDeleting != null)) {
                    this.p3_Get_RegStatsByCombinationRowDeleting(this, new p3_Get_RegStatsByCombinationRowChangeEvent(((p3_Get_RegStatsByCombinationRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void Removep3_Get_RegStatsByCombinationRow(p3_Get_RegStatsByCombinationRow row) {
                this.Rows.Remove(row);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedTableSchema(global::System.Xml.Schema.XmlSchemaSet xs) {
                global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
                global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
                dsCombinationV3 ds = new dsCombinationV3();
                global::System.Xml.Schema.XmlSchemaAny any1 = new global::System.Xml.Schema.XmlSchemaAny();
                any1.Namespace = "http://www.w3.org/2001/XMLSchema";
                any1.MinOccurs = new decimal(0);
                any1.MaxOccurs = decimal.MaxValue;
                any1.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any1);
                global::System.Xml.Schema.XmlSchemaAny any2 = new global::System.Xml.Schema.XmlSchemaAny();
                any2.Namespace = "urn:schemas-microsoft-com:xml-diffgram-v1";
                any2.MinOccurs = new decimal(1);
                any2.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any2);
                global::System.Xml.Schema.XmlSchemaAttribute attribute1 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute1.Name = "namespace";
                attribute1.FixedValue = ds.Namespace;
                type.Attributes.Add(attribute1);
                global::System.Xml.Schema.XmlSchemaAttribute attribute2 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute2.Name = "tableTypeName";
                attribute2.FixedValue = "p3_Get_RegStatsByCombinationDataTable";
                type.Attributes.Add(attribute2);
                type.Particle = sequence;
                global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
                if (xs.Contains(dsSchema.TargetNamespace)) {
                    global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
                    global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
                    try {
                        global::System.Xml.Schema.XmlSchema schema = null;
                        dsSchema.Write(s1);
                        for (global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator(); schemas.MoveNext(); ) {
                            schema = ((global::System.Xml.Schema.XmlSchema)(schemas.Current));
                            s2.SetLength(0);
                            schema.Write(s2);
                            if ((s1.Length == s2.Length)) {
                                s1.Position = 0;
                                s2.Position = 0;
                                for (; ((s1.Position != s1.Length) 
                                            && (s1.ReadByte() == s2.ReadByte())); ) {
                                    ;
                                }
                                if ((s1.Position == s1.Length)) {
                                    return type;
                                }
                            }
                        }
                    }
                    finally {
                        if ((s1 != null)) {
                            s1.Close();
                        }
                        if ((s2 != null)) {
                            s2.Close();
                        }
                    }
                }
                xs.Add(dsSchema);
                return type;
            }
        }
        
        /// <summary>
        ///Represents strongly named DataRow class.
        ///</summary>
        public partial class p3_Get_RegStatsByCombinationRow : global::System.Data.DataRow {
            
            private p3_Get_RegStatsByCombinationDataTable tablep3_Get_RegStatsByCombination;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            internal p3_Get_RegStatsByCombinationRow(global::System.Data.DataRowBuilder rb) : 
                    base(rb) {
                this.tablep3_Get_RegStatsByCombination = ((p3_Get_RegStatsByCombinationDataTable)(this.Table));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string Combination {
                get {
                    try {
                        return ((string)(this[this.tablep3_Get_RegStatsByCombination.CombinationColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'Combination\' in table \'p3_Get_RegStatsByCombination\' is DBN" +
                                "ull.", e);
                    }
                }
                set {
                    this[this.tablep3_Get_RegStatsByCombination.CombinationColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string MunicipalityName {
                get {
                    try {
                        return ((string)(this[this.tablep3_Get_RegStatsByCombination.MunicipalityNameColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'MunicipalityName\' in table \'p3_Get_RegStatsByCombination\' i" +
                                "s DBNull.", e);
                    }
                }
                set {
                    this[this.tablep3_Get_RegStatsByCombination.MunicipalityNameColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public decimal Regular {
                get {
                    try {
                        return ((decimal)(this[this.tablep3_Get_RegStatsByCombination.RegularColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'Regular\' in table \'p3_Get_RegStatsByCombination\' is DBNull." +
                                "", e);
                    }
                }
                set {
                    this[this.tablep3_Get_RegStatsByCombination.RegularColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public decimal ByMail {
                get {
                    try {
                        return ((decimal)(this[this.tablep3_Get_RegStatsByCombination.ByMailColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'ByMail\' in table \'p3_Get_RegStatsByCombination\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tablep3_Get_RegStatsByCombination.ByMailColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public decimal Absentee {
                get {
                    try {
                        return ((decimal)(this[this.tablep3_Get_RegStatsByCombination.AbsenteeColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'Absentee\' in table \'p3_Get_RegStatsByCombination\' is DBNull" +
                                ".", e);
                    }
                }
                set {
                    this[this.tablep3_Get_RegStatsByCombination.AbsenteeColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public decimal Personally {
                get {
                    try {
                        return ((decimal)(this[this.tablep3_Get_RegStatsByCombination.PersonallyColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'Personally\' in table \'p3_Get_RegStatsByCombination\' is DBNu" +
                                "ll.", e);
                    }
                }
                set {
                    this[this.tablep3_Get_RegStatsByCombination.PersonallyColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public decimal UkupnoPrebrojano {
                get {
                    try {
                        return ((decimal)(this[this.tablep3_Get_RegStatsByCombination.UkupnoPrebrojanoColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'UkupnoPrebrojano\' in table \'p3_Get_RegStatsByCombination\' i" +
                                "s DBNull.", e);
                    }
                }
                set {
                    this[this.tablep3_Get_RegStatsByCombination.UkupnoPrebrojanoColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public decimal SpremnoZaBrojanje {
                get {
                    try {
                        return ((decimal)(this[this.tablep3_Get_RegStatsByCombination.SpremnoZaBrojanjeColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'SpremnoZaBrojanje\' in table \'p3_Get_RegStatsByCombination\' " +
                                "is DBNull.", e);
                    }
                }
                set {
                    this[this.tablep3_Get_RegStatsByCombination.SpremnoZaBrojanjeColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public decimal PostaPrebrojano {
                get {
                    try {
                        return ((decimal)(this[this.tablep3_Get_RegStatsByCombination.PostaPrebrojanoColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'PostaPrebrojano\' in table \'p3_Get_RegStatsByCombination\' is" +
                                " DBNull.", e);
                    }
                }
                set {
                    this[this.tablep3_Get_RegStatsByCombination.PostaPrebrojanoColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public decimal OdsustvoPrebrojano {
                get {
                    try {
                        return ((decimal)(this[this.tablep3_Get_RegStatsByCombination.OdsustvoPrebrojanoColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'OdsustvoPrebrojano\' in table \'p3_Get_RegStatsByCombination\'" +
                                " is DBNull.", e);
                    }
                }
                set {
                    this[this.tablep3_Get_RegStatsByCombination.OdsustvoPrebrojanoColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public decimal MobilniPrebrojano {
                get {
                    try {
                        return ((decimal)(this[this.tablep3_Get_RegStatsByCombination.MobilniPrebrojanoColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'MobilniPrebrojano\' in table \'p3_Get_RegStatsByCombination\' " +
                                "is DBNull.", e);
                    }
                }
                set {
                    this[this.tablep3_Get_RegStatsByCombination.MobilniPrebrojanoColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public decimal NepotvrdeniPrebrojano {
                get {
                    try {
                        return ((decimal)(this[this.tablep3_Get_RegStatsByCombination.NepotvrdeniPrebrojanoColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'NepotvrdeniPrebrojano\' in table \'p3_Get_RegStatsByCombinati" +
                                "on\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tablep3_Get_RegStatsByCombination.NepotvrdeniPrebrojanoColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public decimal PostaSpremnoZaBrojanje {
                get {
                    try {
                        return ((decimal)(this[this.tablep3_Get_RegStatsByCombination.PostaSpremnoZaBrojanjeColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'PostaSpremnoZaBrojanje\' in table \'p3_Get_RegStatsByCombinat" +
                                "ion\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tablep3_Get_RegStatsByCombination.PostaSpremnoZaBrojanjeColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public decimal OdsustvoSpremnoZaBrojanje {
                get {
                    try {
                        return ((decimal)(this[this.tablep3_Get_RegStatsByCombination.OdsustvoSpremnoZaBrojanjeColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'OdsustvoSpremnoZaBrojanje\' in table \'p3_Get_RegStatsByCombi" +
                                "nation\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tablep3_Get_RegStatsByCombination.OdsustvoSpremnoZaBrojanjeColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public decimal MobilniSpremnoZaBrojanje {
                get {
                    try {
                        return ((decimal)(this[this.tablep3_Get_RegStatsByCombination.MobilniSpremnoZaBrojanjeColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'MobilniSpremnoZaBrojanje\' in table \'p3_Get_RegStatsByCombin" +
                                "ation\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tablep3_Get_RegStatsByCombination.MobilniSpremnoZaBrojanjeColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public decimal NepotvrdeniSpremnoZaBrojanje {
                get {
                    try {
                        return ((decimal)(this[this.tablep3_Get_RegStatsByCombination.NepotvrdeniSpremnoZaBrojanjeColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'NepotvrdeniSpremnoZaBrojanje\' in table \'p3_Get_RegStatsByCo" +
                                "mbination\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tablep3_Get_RegStatsByCombination.NepotvrdeniSpremnoZaBrojanjeColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsCombinationNull() {
                return this.IsNull(this.tablep3_Get_RegStatsByCombination.CombinationColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetCombinationNull() {
                this[this.tablep3_Get_RegStatsByCombination.CombinationColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsMunicipalityNameNull() {
                return this.IsNull(this.tablep3_Get_RegStatsByCombination.MunicipalityNameColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetMunicipalityNameNull() {
                this[this.tablep3_Get_RegStatsByCombination.MunicipalityNameColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsRegularNull() {
                return this.IsNull(this.tablep3_Get_RegStatsByCombination.RegularColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetRegularNull() {
                this[this.tablep3_Get_RegStatsByCombination.RegularColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsByMailNull() {
                return this.IsNull(this.tablep3_Get_RegStatsByCombination.ByMailColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetByMailNull() {
                this[this.tablep3_Get_RegStatsByCombination.ByMailColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsAbsenteeNull() {
                return this.IsNull(this.tablep3_Get_RegStatsByCombination.AbsenteeColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetAbsenteeNull() {
                this[this.tablep3_Get_RegStatsByCombination.AbsenteeColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsPersonallyNull() {
                return this.IsNull(this.tablep3_Get_RegStatsByCombination.PersonallyColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetPersonallyNull() {
                this[this.tablep3_Get_RegStatsByCombination.PersonallyColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsUkupnoPrebrojanoNull() {
                return this.IsNull(this.tablep3_Get_RegStatsByCombination.UkupnoPrebrojanoColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetUkupnoPrebrojanoNull() {
                this[this.tablep3_Get_RegStatsByCombination.UkupnoPrebrojanoColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsSpremnoZaBrojanjeNull() {
                return this.IsNull(this.tablep3_Get_RegStatsByCombination.SpremnoZaBrojanjeColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetSpremnoZaBrojanjeNull() {
                this[this.tablep3_Get_RegStatsByCombination.SpremnoZaBrojanjeColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsPostaPrebrojanoNull() {
                return this.IsNull(this.tablep3_Get_RegStatsByCombination.PostaPrebrojanoColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetPostaPrebrojanoNull() {
                this[this.tablep3_Get_RegStatsByCombination.PostaPrebrojanoColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsOdsustvoPrebrojanoNull() {
                return this.IsNull(this.tablep3_Get_RegStatsByCombination.OdsustvoPrebrojanoColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetOdsustvoPrebrojanoNull() {
                this[this.tablep3_Get_RegStatsByCombination.OdsustvoPrebrojanoColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsMobilniPrebrojanoNull() {
                return this.IsNull(this.tablep3_Get_RegStatsByCombination.MobilniPrebrojanoColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetMobilniPrebrojanoNull() {
                this[this.tablep3_Get_RegStatsByCombination.MobilniPrebrojanoColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsNepotvrdeniPrebrojanoNull() {
                return this.IsNull(this.tablep3_Get_RegStatsByCombination.NepotvrdeniPrebrojanoColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetNepotvrdeniPrebrojanoNull() {
                this[this.tablep3_Get_RegStatsByCombination.NepotvrdeniPrebrojanoColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsPostaSpremnoZaBrojanjeNull() {
                return this.IsNull(this.tablep3_Get_RegStatsByCombination.PostaSpremnoZaBrojanjeColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetPostaSpremnoZaBrojanjeNull() {
                this[this.tablep3_Get_RegStatsByCombination.PostaSpremnoZaBrojanjeColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsOdsustvoSpremnoZaBrojanjeNull() {
                return this.IsNull(this.tablep3_Get_RegStatsByCombination.OdsustvoSpremnoZaBrojanjeColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetOdsustvoSpremnoZaBrojanjeNull() {
                this[this.tablep3_Get_RegStatsByCombination.OdsustvoSpremnoZaBrojanjeColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsMobilniSpremnoZaBrojanjeNull() {
                return this.IsNull(this.tablep3_Get_RegStatsByCombination.MobilniSpremnoZaBrojanjeColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetMobilniSpremnoZaBrojanjeNull() {
                this[this.tablep3_Get_RegStatsByCombination.MobilniSpremnoZaBrojanjeColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsNepotvrdeniSpremnoZaBrojanjeNull() {
                return this.IsNull(this.tablep3_Get_RegStatsByCombination.NepotvrdeniSpremnoZaBrojanjeColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetNepotvrdeniSpremnoZaBrojanjeNull() {
                this[this.tablep3_Get_RegStatsByCombination.NepotvrdeniSpremnoZaBrojanjeColumn] = global::System.Convert.DBNull;
            }
        }
        
        /// <summary>
        ///Row event argument class
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public class p3_Get_RegStatsByCombinationRowChangeEvent : global::System.EventArgs {
            
            private p3_Get_RegStatsByCombinationRow eventRow;
            
            private global::System.Data.DataRowAction eventAction;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public p3_Get_RegStatsByCombinationRowChangeEvent(p3_Get_RegStatsByCombinationRow row, global::System.Data.DataRowAction action) {
                this.eventRow = row;
                this.eventAction = action;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public p3_Get_RegStatsByCombinationRow Row {
                get {
                    return this.eventRow;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataRowAction Action {
                get {
                    return this.eventAction;
                }
            }
        }
    }
}

#pragma warning restore 1591